# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce34bcf0a22cb8f78d69b78526425f84293a25a81ed0de2086b25ef2ca42f4ef7bd5184688cc6c8110f672cce1b10a9e4262d214ce85faaef831ab920cf49512

test:
  secret_key_base: c895f62cabd3f74bda26eb496e4264e5eb1e06850edfa21bf7b53031462010ff2a66fdbf25b01e06e79d77f6f7444e860a7ecf28aef1f3b60ddccbe701026255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
