        source :gemcutter
        gem "rails", "=3.2.21"
        gem "i18n", ">= 0.5", "< 0.7"
        gem "sqlite3-ruby", :require => "sqlite3"
        gem "rake"
        gem "will_paginate", "~> 3.0.pre2"
        gem "paper_trail_manager", :path => "/home/micah/work/paper_trail_manager"
        gem 'factory_girl_rails', '~> 1.7.0'
        gem 'rspec-rails', '~> 2.11.0'
