name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 3.0
        gemfile:
          - gemfiles/rails_6.0_paper_trail_11.1.gemfile
          - gemfiles/rails_6.0_paper_trail_12.2.gemfile
          - gemfiles/rails_7.0_paper_trail_12.2.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby}}-gems-${{ hashFiles('**/paper_trail_viewer.gemspec') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gems-
          - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      - uses: nanasess/setup-chromedriver@v1.0.1
      - name: install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install
      - name: Generate host app for testing
        run: bundle exec rake generate_spec_app
      - name: Compile JS
        run: npm run compile
      - name: Run RSpec
        run: |
          bundle exec rake spec
